### ISSUE TITLE
libressl not found

### ISSUE THREAD

**Issue by twof** [Ether-CLI/Ether#26]
```swift
$ ether search vapor
dyld: Library not loaded: /usr/local/opt/libressl/lib/libssl.45.dylib
  Referenced from: /usr/local/bin/ether
  Reason: image not found
Abort trap: 6
```

any ideas? Just installed via `brew`

**Comment by calebkleveter** [comment]
Mind trying again? I think I might have fixed it.

**Comment by calebkleveter** [comment]
If you haven't added an access token yet, can you try that? The command is `ether config access-token <token>`.

I'll look into this issue when I have time. I seem to be experiencing it also.

**Comment by calebkleveter** [comment]
Mind updating again? I'm pretty sure I got it fixed.
